core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import home_view, RegisterUserView, LoginStartView, ClaimOrganizationView, before_leaving_organization, leave_organization_confirmed


app_name = 'core'  # take note that the app was called out specifically to avoid conflicts during url such as core:details vs jobs:details

urlpatterns = [
    path('', home_view, name='home'),  # Existing homepage URL
    path('register_user/', RegisterUserView.as_view(), name = 'register'),  # URL for the registration view
    path('login_start/', LoginStartView.as_view(), name = 'login_start'),
    path('logout/', LogoutView.as_view(), name = 'logout'), #there is no logout page, we send back to home, but this code might not work, we might have to override in settings.py

    path('claim_org/', ClaimOrganizationView.as_view(), name='claim_organization'),
    path('leave_org/', before_leaving_organization, name='leaving_organization'), # different treatment for function vs class based views, missing the asview tail
    path('leave_organization/confirm/', leave_organization_confirmed, name='left_organization_confirmation'),

]

job_applications/urls.py
# job_applications/urls.py

from django.urls import path
from django.views.generic.base import RedirectView
from .views import (
    apply_for_job,
    application_accepted,
    my_job_applications,
    view_applications_for_employer,
    employer_application_details,
)
app_name = 'job_applications'

urlpatterns = [
    path('', RedirectView.as_view(url='/'), name='redirect_to_home'),
    path('apply/<int:job_posting_id>/', apply_for_job, name='apply_for_job'),
    path('submitted/<int:application_id>/', application_accepted, name='application_accepted'),
    path('my_applications/', my_job_applications, name='my_job_applications'),
    path('employer_applications/', view_applications_for_employer, name='employer_applications'),
    path('employer_details/<int:application_id>/', employer_application_details, name='employer_application_details'),
]

job_catalog/urls.py
# job_catalog/urls.py, BORROWING THIS PLACEHOLDER TEXT FROM CHATGPT

from django.urls import path
from . import views

app_name = 'job_catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('all_companies/', views.display_all_companies, name='all_companies'),
    path('all_jobs/', views.display_all_jobs, name='all_jobs'),

    path('job/<int:job_id>/', views.job_details, name='job_details'),
    path('company/<int:company_id>/', views.company_details, name='company_details'),

    path('new_org/', views.create_organization, name='create_organization'),

    path('create_job/', views.create_job_posting, name='create_job_posting'),
]

yindeed_proj_name/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),  # Include the URL patterns from the core app
    path('admin/', admin.site.urls),
    path('jobs/', include('job_catalog.urls')),
    path('job_applications/', include('job_applications.urls')),
]

# This conditionally adds media URL patterns for development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Yindeed.com{% endblock title %}</title>
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                {% if request.user.is_authenticated %}
                    <div class="welcome-message py-2 px-3">
                        <strong>{{ request.user.username }}</strong>
                        {% if request.user.profile.organization %}
                            ({{ request.user.profile.organization.employer_org_name }})
                        {% endif %}
                    </div>
                {% endif %}

                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'core:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'job_applications:my_job_applications' %}">My submitted applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'job_catalog:all_companies' %}">All companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'job_catalog:all_jobs' %}">All jobs</a>
                        </li>
                        <!-- Authentication conditional links -->
                        {% if request.user.is_authenticated %}
                            {% if not is_job_poster %}
                                <!-- Employers only section -->
                                <li class="nav-item sidebar-heading px-3 mt-4 mb-1 text-muted">
                                    Prospective employers only:
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'core:claim_organization' %}">Claim organization</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'job_catalog:create_organization' %}">Create organization</a>
                                </li>
                            {% else %}
                                <li class="nav-item sidebar-heading px-3 mt-4 mb-1 text-muted">
                                    Registered employers only:
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'job_applications:employer_applications' %}">View all applications</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'job_catalog:create_job_posting' %}">Create new job posting</a>
                                </li>


                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'job_catalog:company_details' company_id=request.user.profile.organization.id %}">View organization</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link ml-3" href="{% url 'core:leaving_organization' %}">Leave organization</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <form action="{% url 'core:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-link nav-link px-3">Logout</button>
                                </form>
                            </li>

                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:register' %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:login_start' %}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                {% block content %}
                <!-- Page content goes here -->
                {% endblock content %}
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base_generic.html' %}
{% block title %}Yindeed - Home{% endblock title %}
{% block content %}
<!-- Home page content goes here -->
Welcome to Yindeed! Hope you find what you're looking for.
{% endblock content %}