core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import home_view, RegisterUserView, LoginStartView, ClaimOrganizationView, before_leaving_organization, leave_organization_confirmed


app_name = 'core'  # take note that the app was called out specifically to avoid conflicts during url such as core:details vs jobs:details

urlpatterns = [
    path('', home_view, name='home'),  # Existing homepage URL
    path('register_user/', RegisterUserView.as_view(), name = 'register'),  # URL for the registration view
    path('login_start/', LoginStartView.as_view(), name = 'login_start'),
    path('logout/', LogoutView.as_view(), name = 'logout'), #there is no logout page, we send back to home, but this code might not work, we might have to override in settings.py

    path('claim_org/', ClaimOrganizationView.as_view(), name='claim_organization'),
    path('leave_org/', before_leaving_organization, name='leaving_organization'), # different treatment for function vs class based views, missing the asview tail
    path('leave_organization/confirm/', leave_organization_confirmed, name='left_organization_confirmation'),

]

job_applications/urls.py
# job_applications/urls.py

from django.urls import path
from django.views.generic.base import RedirectView
from .views import (
    apply_for_job,
    application_accepted,
    my_job_applications,
    view_applications_for_employer,
    employer_application_details,
)
app_name = 'job_applications'

urlpatterns = [
    path('', RedirectView.as_view(url='/'), name='redirect_to_home'),
    path('apply/<int:job_posting_id>/', apply_for_job, name='apply_for_job'),
    path('submitted/<int:application_id>/', application_accepted, name='application_accepted'),
    path('my_applications/', my_job_applications, name='my_job_applications'),
    path('employer_applications/', view_applications_for_employer, name='employer_applications'),
    path('employer_details/<int:application_id>/', employer_application_details, name='employer_application_details'),
]

job_catalog/urls.py
# job_catalog/urls.py, BORROWING THIS PLACEHOLDER TEXT FROM CHATGPT

from django.urls import path
from . import views

app_name = 'job_catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('all_companies/', views.display_all_companies, name='all_companies'),
    path('all_jobs/', views.display_all_jobs, name='all_jobs'),

    path('job/<int:job_id>/', views.job_details, name='job_details'),
    path('company/<int:company_id>/', views.company_details, name='company_details'),

    path('new_org/', views.create_organization, name='create_organization'),

    path('create_job/', views.create_job_posting, name='create_job_posting'),
]

yindeed_proj_name/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),  # Include the URL patterns from the core app
    path('admin/', admin.site.urls),
    path('jobs/', include('job_catalog.urls')),
    path('job_applications/', include('job_applications.urls')),
]

# This conditionally adds media URL patterns for development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job_catalog/models.py
#TODO: plan for industry tags, maybe so that users can only find orgs in their preferred industry


from django.db import models
from django.utils import timezone  #need this or we can't auto-set dates of job posting originations
# Create your models here.

class EmployerOrganization(models.Model):
    employer_org_name = models.CharField(max_length = 50)
    employer_org_description_box = models.TextField(
        default = 'Describe your organization, but not a specific role or requirements',
        blank = False  #we do not allow job posters to create employer orgs without a description
        )
    representative_claim_token = models.CharField(max_length = 16, default = "join")
    def __str__(self):
        return self.employer_org_name


class JobPosting(models.Model):
    organization = models.ForeignKey(EmployerOrganization, on_delete=models.CASCADE, default = 1)  #we wanted cascaded deletion but FYI django requires explicit selection of on_delete
    title = models.CharField(max_length=100)
    role_overview = models.TextField()
    role_requirements_and_preferences = models.TextField()
    action_steps = models.TextField()
    post_date = models.DateTimeField(auto_now=True)
    expiration_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(days=90))
    is_active = models.BooleanField(default=True)

    # Override the save method to check expiration date and set is_active
    def save(self, *args, **kwargs):
        if self.expiration_date < timezone.now():
            self.is_active = False
        super().save(*args, **kwargs)

job_catalog/forms.py
# job_catalog/forms.py

from django import forms
from .models import EmployerOrganization, JobPosting

class EmployerOrganizationForm(forms.ModelForm):
    class Meta:
        model = EmployerOrganization
        fields = ['employer_org_name', 'employer_org_description_box', 'representative_claim_token']
        # Add any additional fields you'd like to include in the form

class JobPostingForm(forms.ModelForm):
    class Meta:
        model = JobPosting
        fields = ['title', 'role_overview', 'role_requirements_and_preferences', 'action_steps',]
        # Exclude 'expiration_date' from the form

job_catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib import messages

from .forms import EmployerOrganizationForm, JobPostingForm

from django.http import HttpResponse

from .models import EmployerOrganization, JobPosting #have to pull from the models to list them all
from core.models import UserProfile
from job_applications.models import JobApplication  # Adjust the import path according to your project structure

from django.urls import reverse
from django.utils import timezone


def index(request):
    return HttpResponse("Job Catalog app section")

def display_all_companies(request):  #not sure where "request" comes from
    all_organizations = EmployerOrganization.objects.all()
    context = {'organizations_list': all_organizations}  # we are declaring, not pulling variables here
    return render(request, 'job_catalog/all_companies.html' ,context)  #the 2nd argument auto-requested a template_name, and it will default to the templates folder as the root



def display_all_jobs(request):
    all_jobs = JobPosting.objects.all()
    context = {'job_postings_list': all_jobs}  # we are declaring, not pulling variables here
    return render(request, 'job_catalog/all_jobs.html' ,context)


def job_details(request, job_id):
    job_instance = get_object_or_404(JobPosting, pk=job_id)
    user_has_applied = False
    application = None

    if request.user.is_authenticated:
        try:
            application = JobApplication.objects.get(job_posting=job_instance, user=request.user)
            user_has_applied = True
        except JobApplication.DoesNotExist:
            user_has_applied = False

    context = {
        'job_instance': job_instance,
        'user_has_applied': user_has_applied,
        'application': application,  # Optional: Only if you need more details from the application itself
    }
    return render(request, 'job_catalog/job_details.html', context)

def company_details(request, company_id):
    company_instance = get_object_or_404(EmployerOrganization, pk=company_id)
    total_job_postings = JobPosting.objects.filter(organization=company_instance).count()
    active_job_postings = JobPosting.objects.filter(organization=company_instance, is_active=True).count()
    job_postings = JobPosting.objects.filter(organization=company_instance, is_active=True)

    context = {
        'company_instance': company_instance,
        'job_postings': job_postings,
        'total_job_postings': total_job_postings,  # Total number of jobs posted
        'active_job_postings': active_job_postings,  # Number of active jobs
    }
    return render(request, 'job_catalog/company_details.html', context)


def create_organization(request):
    # Check if the user is logged in and doesn't already belong to an organization
    if not request.user.is_authenticated:
        messages.error(request, "You must be logged in to create an organization.")
        return redirect('core:login_start')

    user_profile = UserProfile.objects.get(user=request.user)
    if user_profile.organization:
        org_name = user_profile.organization.employer_org_name
        messages.error(request,
                       f"You cannot create a company since you are currently representing {org_name} for hiring.")
        return redirect('job_catalog:index')  # Adjust as needed

    if request.method == 'POST':
        form = EmployerOrganizationForm(request.POST)
        if form.is_valid():
            new_organization = form.save()
            user_profile.organization = new_organization
            user_profile.save()
            messages.success(request, "Organization created successfully.")
            return redirect('job_catalog:index')  # Redirect to an appropriate page
    else:
        form = EmployerOrganizationForm()

    return render(request, 'job_catalog/create_organization_form.html', {'form': form})

def create_job_posting(request):
    print("Entered create_job_posting view")
    if not request.user.is_authenticated:
        messages.error(request, "You must be logged in to post a job.")
        return redirect('core:login_start')

    if not hasattr(request.user, 'profile') or not request.user.profile.organization:
        messages.error(request, "You need to be associated with an organization to post a job.")
        return redirect('/')  # Redirect to the home page if not associated with an organization

    if request.method == 'POST':
        form = JobPostingForm(request.POST)
        print("Form created")
        if form.is_valid():
            print("Form is valid")
            job_posting = form.save(commit=False)
            job_posting.organization = request.user.profile.organization  # Associate the job posting with the organization
            # Set the post date to now and calculate the expiration date
            job_posting.post_date = timezone.now()
            job_posting.expiration_date = timezone.now() + timezone.timedelta(days=90)
            job_posting.save()
            print(f"Job Posting created with ID: {job_posting.id}")
            messages.success(request, 'Job posting created successfully.')
            return redirect(reverse('job_catalog:job_details', args=[job_posting.id]))
        else:
            # This block will execute if form is not valid
            print("Form is not valid")
            print(form.errors)
    else:
        form = JobPostingForm()

    return render(request, 'job_catalog/create_job_posting.html', {'form': form})

templates/job_catalog/all_companies.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h2>All Companies</h2>
    <ul>
    {% for organization in organizations_list %}
        <li>
            <a href = "{% url 'job_catalog:company_details' organization.id %}">{{ organization.employer_org_name }}</a>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/job_catalog/all_jobs.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h2>All Jobs</h2>
    <ul>
    {% for job_posting in job_postings_list %}
        <li>
            <a href="{% url 'job_catalog:job_details' job_posting.id %}">
                {{ job_posting.id }}: {{ job_posting.title }}
            </a>
            @
            <a href="{% url 'job_catalog:company_details' job_posting.organization.id %}">
                {{ job_posting.organization.employer_org_name }}
            </a>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/job_catalog/company_details.html
{% extends 'base_generic.html' %}

{% block title %}{{ company_instance.employer_org_name }}{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ company_instance.employer_org_name }}</h1>
    <br>
    <h4>Company overview:</h4>
    <p>{{ company_instance.employer_org_description_box }}</p>
    <br><br>
    <!-- List of Job Postings for the company -->
    <h4>Job Postings at {{ company_instance.employer_org_name }}</h4>
    {% if total_job_postings == 0 %}
        <p>{{ company_instance.employer_org_name }} hasn't posted their first job yet.</p>
    {% else %}
        <p>{{ company_instance.employer_org_name }} has posted {{ total_job_postings }} job{{ total_job_postings|pluralize }}, {{ active_job_postings }} of which {{ active_job_postings|pluralize:"is,are" }} still active.</p>
        {% if job_postings %}
            <ul>
                {% for job in job_postings %}
                    <li>
                        <strong><a href="{% url 'job_catalog:job_details' job.id %}">{{ job.title }}</a></strong><br>
                        <p>{{ job.role_overview }}</p>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/job_catalog/create_job_posting.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Creating a new job posting</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-field">
            <strong>Title:</strong><br>
            {{ form.title }}<br>
            <br>
        </div>
        <div class="form-field">
            <strong>Role Overview:</strong><br>
            {{ form.role_overview }}<br>
            <br>
        </div>
        <div class="form-field">
            <strong>Role Requirements and Preferences:</strong><br>
            {{ form.role_requirements_and_preferences }}<br>
            <br>
        </div>
        <div class="form-field">
            <strong>Action Steps:</strong><br>
            {{ form.action_steps }}<br>
            <br>
        </div>
        <!-- Since 'expiration_date' and 'is_active' are managed by the system, they are not included in the form -->
        <button type="submit" class="btn btn-primary">Create new job posting</button>
    </form>
</div>

<style>
    input[type='text'], textarea {
        width: 100%; /* Or any other width you prefer */
        max-width: 100%; /* To ensure it doesn't exceed the width of its container */
    }
</style>

{% endblock content %}

templates/job_catalog/create_organization_form.html
{% extends 'base_generic.html' %}  <!-- Replace with your actual base template name -->

{% block content %}
<div class="container">
    <h1 class="mt-4">Tell us about your unlisted organization!</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="employer_org_name">Employer Org Name:</label>
            <input type="text" class="form-control" id="employer_org_name" name="employer_org_name">
        </div>
        <div class="form-group">
            <label for="employer_org_description_box">Employer Org Description Box:</label>
            <textarea class="form-control" id="employer_org_description_box" name="employer_org_description_box"></textarea>
        </div>
      <div class="form-group">
          <label for="representative_claim_token">Representative Claim Token:</label>
          <input type="text" class="form-control" id="representative_claim_token" name="representative_claim_token" style="width: 30%;" placeholder="Enter token">
      </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/job_catalog/job_details.html
{% extends 'base_generic.html' %}

{% block title %}{{ job_instance.title }}{% endblock %}

{% block content %}
<div class="container">
    <h3>{{ job_instance.title }}</h3>
    <!-- Make the organization name a link to its details page -->
    <h4>(<a href="{% url 'job_catalog:company_details' company_id=job_instance.organization.id %}">{{ job_instance.organization }}</a>)</h4>
    <br>
    <p><strong>Role overview:</strong><br>{{ job_instance.role_overview }}</p>
    <p><strong>Requirements + Preferences:</strong><br>{{ job_instance.role_requirements_and_preferences }}</p>
    <p><strong>Instructions:</strong><br>{{ job_instance.action_steps }}</p>
    <p><strong>Posted On:</strong> {{ job_instance.post_date }}</p>
    <p><strong>Job Posting ID:</strong> {{ job_instance.id }}</p>

    <!-- User authentication and application status check -->
    <br>
    {% if user.is_authenticated %}
        {% if user_has_applied %}
            <p>You have already applied for this job on {{ application.submit_date }}.</p>
        {% else %}
            <a href="{% url 'job_applications:apply_for_job' job_posting_id=job_instance.id %}" class="btn btn-primary">Apply for This Job</a>
        {% endif %}
    {% else %}
        <p>To apply for this role, <a href="{% url 'core:login_start' %}">log in</a> first.</p>
    {% endif %}
</div>
{% endblock %}